version: "3"

networks:
    laravel:

services:

    php:
        user: "${UID}:${GID}"
        build:
            context: ./images/php
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - 9000:9000
        networks:
            - laravel

    mysql:
        image: mariadb
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: reviews
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel

    pma:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        restart: always
        links:
            - mysql:mysql
        ports:
            - 8080:80
        environment: 
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: secret
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel

    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www/html/
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx:/var/log/nginx
        depends_on:
            - php
            - mysql
        networks:
            - laravel
