version: "3.8"

networks:
    laravel:

services:

    php:
        build:
            context: ./images/php
            dockerfile: Dockerfile
            args:
                UNAME: ${UNAME}
                UID: ${UID}
                GID: ${GID}
        container_name: laravel_reviews_php
        tty: true
        ports:
            - 9000:9000
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    mysql:
        image: mariadb
        container_name: laravel_reviews_mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: reviews
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel

    pma:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_reviews_pma
        restart: always
        links:
            - mysql:mysql
        ports:
            - 8080:80
        environment: 
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: secret
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel

    nginx:
        image: nginx:stable
        container_name: laravel_reviews_nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www/html/
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx:/var/log/nginx
        depends_on:
            - php
            - mysql
        networks:
            - laravel
